name: Hourly Dip Scanner

on:
  schedule:
    - cron: "0 * * * *"   # hourly, UTC
  workflow_dispatch:      # allow manual run

jobs:
  run-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scanner
        env:
          SCAN_SAVE_DIR: data
        run: |
          python scanner.py

      - name: Commit results (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mkdir -p data
          git add data || true
          git diff --staged --quiet || git commit -m "scan: update $(date -u +'%Y-%m-%dT%H:%MZ')" || echo "No changes"
          git push
